### PR TITLE
chore: update qg-checklist

### PR DESCRIPTION
**Pull request by RoKrish14**
Updated the QG checklist for TRG 8 Security

## Description
This PR updates the QG checks related to TRG 8 Security
- added security related TRG Checks for the next release e.g TRG 8.X
- added links to TRG 8.01, 8.02, 8.03, 8.04

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by FaGru3n** [comment]
Hi @RoKrish14 

thanks for the contribution. Just a little clarification for myself...

Are the workflows for security mandatory or just a "should" be implemented? At least when could we check the checkbox, when worflow is there or how we could validate the TRG´s?

**Review by SebastianBezold — APPROVED** [review]
I think it is good to add it to the review template, simply to have a reminder. 
But similar to @FaGru3n, I personally am not sure, how I would review this topics. Is it just verifying, if workflows are present? Is there guidance from the security team, how committers can review these topics, or does it always have to be reviewed by security experts

**Comment by RoKrish14** [comment]
Hey @FaGru3n, @SebastianBezold,
1. The workflows for security (TRG 8.01-04) are mandatory and the box should be checked if the security checks has been approved.
2. As of now, the validation of the security checks are done by the security team. But going forward, it would be committers themselves who need to keep a check on the TRG for security.

I assume that this checklist is the one that is required to perform QG checks before the release, wherein, once the checks are approved, the checkboxes are ticked. Please correct me if I am looking at it differently.

**Comment by FaGru3n** [comment]
> Hey @FaGru3n, @SebastianBezold,
> 
> 1. The workflows for security (TRG 8.01-04) are mandatory and the box should be checked if the security checks has been approved.
> 2. As of now, the validation of the security checks are done by the security team. But going forward, it would be committers themselves who need to keep a check on the TRG for security.
> 
> I assume that this checklist is the one that is required to perform QG checks before the release, wherein, once the checks are approved, the checkboxes are ticked. Please correct me if I am looking at it differently.

Thanks for the clarification, with this info for me it would be ok to keep it as a little reminder. But would assume that this should be communicated to all of our committers. @RoKrish14 Maybe you could present it in the committer meetings or some similar round the inform everyone.

**Review by FaGru3n — APPROVED** [review]

**Comment by RoKrish14** [comment]
Would it be better if I modify the content like:
- [ ] [TRG 8.01](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01) Mitigate high and above findings in CodeQL
- [ ] [TRG 8.02](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02) Mitigate high and above findings in KICS
- [ ] [TRG 8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03) Mitigate high and above findings in Gitguardian
- [ ] [TRG 8.04](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04) Mitigate high and above findings in Trivy

**Review by FaGru3n — APPROVED** [review]

**Review by SebastianBezold — APPROVED** [review]

**Pull request merged**
