### PR TITLE
chore(qg-checklist): update issue-template

### PR DESCRIPTION
**Pull request by FaGru3n**
#### What would be changed or will be added with this PR?
- added more TRG Checks for the next release e.g TRG 7.X
- added prefixed hyperlinks to each TRG 
- made TRG specific checks collapsible within the issue
#### Why do i want to change this?
- easier issue creation with defined issue subjects for each TRG
- option to generate issues specifc for the TRG Check also with defined issue subjects
#### Testing
- check out branch `chore/update-trg-checklist`
- Review `system-team-qg-checklist.md` in your IDE with markdown preview
#### Visualisation
image

#### Additional information
updates eclipse-tractusx/sig-infra#61

[FaGru3n](https://github.com/FaGru3n), Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

### CODE REVIEW

**Review by hzierer — APPROVED** [review]
LGTM

**Review by carslen — APPROVED** [review]
LGTM

**Review by AngelikaWittek — COMMENTED** [review]
Please add TRG 7.06 and 7.07

**Comment by FaGru3n** [comment]
Hi @AngelikaWittek updated my branch: 
> Please add TRG 7.06 and 7.07
https://github.com/eclipse-tractusx/.github/pull/7/commits/2dee7bd42e4d1873c644595a1eccf4fa88e4c32a

Please check again 😃

**Comment by AngelikaWittek** [comment]
I would rather not mention the summary details of TRG 7.06, as in the description is an example and the hint to use the shared components.

**Comment by FaGru3n** [comment]
> I would rather not mention the summary details of TRG 7.06, as in the description is an example and the hint to use the shared components.

[chore(qg-checklist): sum-up TRG 7.06 details](https://github.com/eclipse-tractusx/.github/pull/7/commits/ae4d86d74ad9150db98b7efba00756d45fad17b6)

@AngelikaWittek thanks for your feedback

**Comment by AngelikaWittek** [comment]
Thank you. Looks good to me.

**Review by AngelikaWittek — APPROVED** [review]
looks good to me

**Comment by FaGru3n** [comment]
FYI @Siegfriedk

**Pull request merged**
